// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     alert.avsc
 *     candidate.avsc
 *     cutout.avsc
 *     prv_candidate.avsc
 */
package schema

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/container"
	"github.com/actgardner/gogen-avro/v7/vm"
)

func NewAlertWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewAlert()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type AlertReader struct {
	r io.Reader
	p *vm.Program
}

func NewAlertReader(r io.Reader) (*AlertReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewAlert()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &AlertReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r AlertReader) Read() (*Alert, error) {
	t := NewAlert()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
