// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     alert.avsc
 *     candidate.avsc
 *     cutout.avsc
 *     prv_candidate.avsc
 */
package schema

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type UnionNullCutoutTypeEnum int

const (
	UnionNullCutoutTypeEnumCutout UnionNullCutoutTypeEnum = 1
)

type UnionNullCutout struct {
	Null      *types.NullVal
	Cutout    *Cutout
	UnionType UnionNullCutoutTypeEnum
}

func writeUnionNullCutout(r *UnionNullCutout, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullCutoutTypeEnumCutout:
		return writeCutout(r.Cutout, w)
	}
	return fmt.Errorf("invalid value for *UnionNullCutout")
}

func NewUnionNullCutout() *UnionNullCutout {
	return &UnionNullCutout{}
}

func (_ *UnionNullCutout) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullCutout) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullCutout) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullCutout) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullCutout) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullCutout) SetString(v string)  { panic("Unsupported operation") }
func (r *UnionNullCutout) SetLong(v int64) {
	r.UnionType = (UnionNullCutoutTypeEnum)(v)
}
func (r *UnionNullCutout) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		r.Cutout = NewCutout()
		return r.Cutout
	}
	panic("Unknown field index")
}
func (_ *UnionNullCutout) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullCutout) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullCutout) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullCutout) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullCutout) Finalize()                        {}

func (r *UnionNullCutout) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case UnionNullCutoutTypeEnumCutout:
		return json.Marshal(map[string]interface{}{"cutout": r.Cutout})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullCutout")
}

func (r *UnionNullCutout) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["cutout"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Cutout)
	}
	return fmt.Errorf("invalid value for *UnionNullCutout")
}
