// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCES:
 *     alert.avsc
 *     candidate.avsc
 *     cutout.avsc
 *     prv_candidate.avsc
 */
package schema

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type UnionNullFloatTypeEnum int

const (
	UnionNullFloatTypeEnumFloat UnionNullFloatTypeEnum = 1
)

type UnionNullFloat struct {
	Null      *types.NullVal
	Float     float32
	UnionType UnionNullFloatTypeEnum
}

func writeUnionNullFloat(r *UnionNullFloat, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullFloatTypeEnumFloat:
		return vm.WriteFloat(r.Float, w)
	}
	return fmt.Errorf("invalid value for *UnionNullFloat")
}

func NewUnionNullFloat() *UnionNullFloat {
	return &UnionNullFloat{}
}

func (_ *UnionNullFloat) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetString(v string)  { panic("Unsupported operation") }
func (r *UnionNullFloat) SetLong(v int64) {
	r.UnionType = (UnionNullFloatTypeEnum)(v)
}
func (r *UnionNullFloat) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		return &types.Float{Target: (&r.Float)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullFloat) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullFloat) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullFloat) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullFloat) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullFloat) Finalize()                        {}

func (r *UnionNullFloat) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case UnionNullFloatTypeEnumFloat:
		return json.Marshal(map[string]interface{}{"float": r.Float})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullFloat")
}

func (r *UnionNullFloat) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["float"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Float)
	}
	return fmt.Errorf("invalid value for *UnionNullFloat")
}
